#ifndef __SENSOR_WEB_CONFIG_H_
#define __SENSOR_WEB_CONFIG_H_

String SENSOR_ID = "[YOUR_SENSOR_ID]";
String API_KEY = "[YOUR_API_KEY]";
String SERVER_ADDRESS = "127.0.0.1";
int SERVER_PORT = 3000;

#endif /* __SENSOR_WEB_CONFIG_H_ */
